bad-build:
	docker build -t dwmkerr/ece-psp-bad -f Dockerfile.bad .

bad-run:
	docker run -it -p 3001:8080 dwmkerr/ece-psp-bad

good-build:
	docker build -t dwmkerr/ece-psp-good -f Dockerfile.good .

good-run:
	docker run -it -p 3002:8080 dwmkerr/ece-psp-good
